### ISSUE TITLE
Still an active project?

### ISSUE THREAD

**Issue by notrab** [01-studio/next-graphql#16]
Hey 👋🏻 

I just spent the morning creating something similar to this library for an upcoming workshop on GraphQL, and then I found this when accidentally typing the package name into NPM.

Is this package still maintained? If so, would you be open to collaborating on it?

Here's what I have: https://github.com/notrab/next-graphql-handler which is pretty similar -- only difference is I render GraphiQL and it doesn't yet support directives.

Thank you 🙏🏻

**Comment by ian** [comment]
I would recommend graphql-request or urql at this point.  The tie-ins to graphql-code-generator are pretty powerful and the libraries are very well maintained.
